### ISSUE TITLE
Enhance pre-commit hook to lint multiple files at once

### ISSUE THREAD

**Issue by mbarbin** [mbarbin/dunolint#60]
In #53 we discussed that we could possibly make dunolint support linting multiple files specified at once, since this is how the pre-commit tool works.

As of now, the hook is configured such that there is 1 call to dunolint *per file*. We could consider making that 1 call *per invocation*.

In practice, this only affects commits that touches multiple dune files.

Tracked by this issue to remind us to consider whether we want to act on this plan later.

**Comment by mbarbin** [comment]
Quoting from #53 :

> > Perhaps the easiest thing to do is to split this into a separate tool, dunolint tools lint-file-in-place ?
>
> I guess, yes. I suppose it is also possible to add more CLI validation and allow multiple positional arguments when in the in-place mode only. I'm not sure which of these 2 options I prefer, I'll think a bit about it.

Currently the file is:
```yml
---
- id: dunolint
  name: Dunolint
  description: Linter and formatter for Dune files
  language: system
  entry: bash -c 'for n in $(seq 0 "$#"); do dunolint tools lint-file --in-place "${!n}"; done'
  files: "^(.*/)?dune(-project)?$"
```

(See the bash for-loop).
